In [1]:
from pyautodiff.optimizer import Optimizer
import pyautodiff.admath as admath
import numpy as np
from sklearn.datasets import make_regression, make_classification


# Creates a regression problem with 3 features
X,y,coef = make_regression(n_features=3,n_informative=3,coef=True)

# User defined loss function
def user_mse(y,y_preds):
    return (y-y_preds)**2


opt = Optimizer(loss=user_mse,optimizer='sgd',regularizer='ridge',lam=0.01)
opt.fit(X,y,iters=2000)

print('Actual Values:')
print('======')
print(coef)


print('Computed Values:')
print('======')
print(opt.coefs)
print(opt.score(X,y))


# Creates a classification problem with 3 features
X2,y2 = make_classification(n_features=3,n_informative=3,n_redundant=0)

def user_cross_entropy(y,y_preds):
    if y == 1:
        return -admath.log(y_preds)
    else:
        return -admath.log(1-y_preds)


opt = Optimizer(loss=user_cross_entropy,optimizer='sgd',regularizer='ridge',lam=0.01,problem_type='classification')
opt.fit(X2,y2,iters=2500)
y_preds = opt.predict(X2)

print('Computed Values:')
print('======')
print(opt.coefs)
print(opt.score(X2,y2))


Actual Values:
[35.74862999 41.05973634 96.79065865]
Computed Values:
[35.43642643 40.661732   95.6785281 ]
0.999876769529266
Computed Values:
[-0.81266023 -0.61424104  1.75035556]
0.89


In [2]:
from pyautodiff.optimizer import Optimizer
import pyautodiff.admath as admath
import numpy as np
from sklearn.datasets import make_regression, make_classification

In [3]:
# Creates a regression problem with 3 features
X,y,coef = make_regression(n_features=3,n_informative=3,coef=True)

# User defined loss function
def user_mse(y,y_preds):
    return (y-y_preds)**2


opt = Optimizer(loss=user_mse,optimizer='sgd',regularizer='ridge',lam=0.01)
opt.fit(X,y,iters=2000)

In [4]:
print('Actual Values:')
print('======')
print(coef)

Actual Values:
[30.07204601 43.41353    42.64089004]


In [5]:
print('Computed Values:')
print('======')
print(opt.coefs)
print(opt.score(X,y))

Computed Values:
[29.66170534 42.79584969 42.24348357]
0.9998503971809333
