In [1]:
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

df = pd.DataFrame({"A": [10,20,30,40,50], "B": [20, 30, 10, 40, 50], "C": [32, 234, 23, 23, 42523]})
model = sm.OLS(df['A'].values, sm.add_constant(df[['B', 'C']])).fit()
# model = sm.OLS(formula="A ~ B + C", data=df).fit()

In [2]:
model.params

const    14.952480
B         0.401182
C         0.000352
dtype: float64

In [3]:
model.summary()

/Users/pwong/anaconda3/lib/python3.6/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.579
Model:                            OLS   Adj. R-squared:                  0.158
Method:                 Least Squares   F-statistic:                     1.375
Date:                Sun, 09 Dec 2018   Prob (F-statistic):              0.421
Time:                        19:15:10   Log-Likelihood:                -18.178
No. Observations:                   5   AIC:                             42.36
Df Residuals:                       2   BIC:                             41.19
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         14.9525     17.764      0.842      0.489     -61.481      91.386
B              0.4012      0.650      0.617      0.600      -2.394       3.197
C              0.0004      0.001      0.650      0.583      -0.002       0.003
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.061
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.498
Skew:                          -0.123   Prob(JB):                        0.780
Kurtosis:                       1.474   Cond. No.                     5.21e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.21e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [4]:
socio_data = pd.read_stata('gsswide.dta')

In [5]:
socio_data.dtypes

id             int16
papres16        int8
paeduc          int8
maeduc          int8
educ            int8
year            int8
black           int8
male            int8
parfor          int8
hsgrad          int8
colgrad         int8
edcat       category
dtype: object

In [6]:
socio_data.head()

id  papres16  paeduc  maeduc  educ  year  black  male  parfor  hsgrad  \
0   1        50      16      12    16    86      0     0       0       1   
1   2        42      16      16    16    86      0     0       0       1   
2   3        47      12      12    18    86      0     1       0       1   
3   4        78      19      16    17    86      0     0       0       1   
4   5        41      16      12    18    86      0     1       0       1   

   colgrad    edcat  
0        1  ColGrad  
1        1  ColGrad  
2        1  GradSch  
3        1  GradSch  
4        1  GradSch

In [83]:
y = socio_data['educ'].values
# X = sm.add_constant() #, 'black', 'male']])#[[x_paeduc, x_maeduc, x_black, x_male ]]
X = socio_data[['papres16','paeduc', 'maeduc']]

In [87]:
from sklearn.linear_model import LinearRegression



In [88]:
lr = LinearRegression().fit(X,y)

In [90]:
lr.coef_

array([0.02047952, 0.18010059, 0.25747745])

In [93]:
np.max(X)

papres16    82
paeduc      20
maeduc      20
dtype: int8

In [91]:
opt.fit(np.array(X), y, iters=100)


/Users/pwong/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [92]:
opt.coefs

array([1.18416393e+152, 3.80610916e+151, 2.84179254e+151])

In [75]:
model = sm.OLS(y, X)
result = model.fit()

In [76]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.304
Model:                            OLS   Adj. R-squared:                  0.303
Method:                 Least Squares   F-statistic:                     662.0
Date:                Sun, 09 Dec 2018   Prob (F-statistic):               0.00
Time:                        19:41:14   Log-Likelihood:                -10774.
No. Observations:                4552   AIC:                         2.156e+04
Df Residuals:                    4548   BIC:                         2.158e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.8382      0.146     53.659      0.000       7.552       8.125
papres16       0.0205      0.003      6.176      0.000       0.014       0.027
paeduc         0.1801      0.013     13.726      0.000       0.154       0.206
maeduc         0.2575      0.015     17.705      0.000       0.229       0.286
==============================================================================
Omnibus:                      118.093   Durbin-Watson:                   1.825
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              233.378
Skew:                           0.169   Prob(JB):                     2.10e-51
Kurtosis:                       4.056   Cond. No.                         175.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
result.params

const       7.812613
papres16    0.019210
paeduc      0.179124
maeduc      0.253879
black      -0.346477
male        0.374384
dtype: float64

## Optimizer example

In [11]:
from pyautodiff.optimizer import Optimizer

In [20]:
import numpy as np

In [14]:
opt = Optimizer(loss = 'mse', optimizer = 'sgd')

In [77]:
y = socio_data['educ'].values
X = socio_data[['papres16','paeduc', 'maeduc']]#, 'black', 'male']]#[[x_paeduc, x_maeduc, x_black, x_male ]]

In [78]:
X_array = np.array(X)

In [79]:
X_array[:5], X[:5]

(array([[50, 16, 12],
        [42, 16, 16],
        [47, 12, 12],
        [78, 19, 16],
        [41, 16, 12]], dtype=int8),    papres16  paeduc  maeduc
 0        50      16      12
 1        42      16      16
 2        47      12      12
 3        78      19      16
 4        41      16      12)

In [53]:
np.array(y).shape, X_array.shape

((4552,), (4552, 5))

In [40]:
# np.amax(X_array, axis=0)

array([ 1., 82., 20., 20.,  1.,  1.])

In [80]:
opt.fit(X_array, y, iters=100)

/Users/pwong/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/Users/pwong/Documents/cs207-FinalProject/pyautodiff/optimizer.py:123: RuntimeWarning: overflow encountered in square
  return np.sum((y-y_preds)**2)/len(y)
/Users/pwong/Documents/cs207-FinalProject/pyautodiff/dual.py:210: RuntimeWarning: overflow encountered in double_scalars
  return Dual(self.val ** other, temp)


In [81]:
opt.coefs

array([-1.55504049e+156, -4.20604066e+155, -4.22770658e+155])

In [82]:
result.params

const       7.838184
papres16    0.020480
paeduc      0.180101
maeduc      0.257477
dtype: float64

In [36]:
from sklearn.datasets import make_regression

In [41]:
np.amax(X, axis=0)

array([3.49743749, 4.09623193, 4.04712938, 3.33472592, 3.4573205 ,
       3.05651632])

In [71]:
X,y,coef = make_regression(n_samples=4500,n_features=6,n_informative=6,coef=True)

# User defined loss function
# def user_mse(y,y_preds):
#     return (y-y_preds)**2


opt = Optimizer(loss='mse',optimizer='sgd')
opt.fit(X,y,iters=1000)

print('Actual Values:')
print('======')
print(coef)

print('Computed Values:')
print('======')
print(opt.coefs)

Actual Values:
[13.04355993 68.32081412  1.81041096 22.60987421 28.47926702 77.75625355]
Computed Values:
[13.04355992 68.32081402  1.81041105 22.60987426 28.47926695 77.75625341]
