In [1]:
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

df = pd.DataFrame({"A": [10,20,30,40,50], "B": [20, 30, 10, 40, 50], "C": [32, 234, 23, 23, 42523]})
model = sm.OLS(df['A'].values, sm.add_constant(df[['B', 'C']])).fit()
# model = sm.OLS(formula="A ~ B + C", data=df).fit()

In [2]:
model.params

const    14.952480
B         0.401182
C         0.000352
dtype: float64

In [3]:
model.summary()

/Users/pwong/anaconda3/lib/python3.6/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.579
Model:                            OLS   Adj. R-squared:                  0.158
Method:                 Least Squares   F-statistic:                     1.375
Date:                Sun, 09 Dec 2018   Prob (F-statistic):              0.421
Time:                        19:15:10   Log-Likelihood:                -18.178
No. Observations:                   5   AIC:                             42.36
Df Residuals:                       2   BIC:                             41.19
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         14.9525     17.764      0.842      0.489     -61.481      91.386
B              0.4012      0.650      0.617      0.600      -2.394       3.197
C              0.0004      0.001      0.650      0.583      -0.002       0.003
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.061
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.498
Skew:                          -0.123   Prob(JB):                        0.780
Kurtosis:                       1.474   Cond. No.                     5.21e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.21e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [4]:
socio_data = pd.read_stata('gsswide.dta')

In [5]:
socio_data.dtypes

id             int16
papres16        int8
paeduc          int8
maeduc          int8
educ            int8
year            int8
black           int8
male            int8
parfor          int8
hsgrad          int8
colgrad         int8
edcat       category
dtype: object

In [6]:
socio_data.head()

id  papres16  paeduc  maeduc  educ  year  black  male  parfor  hsgrad  \
0   1        50      16      12    16    86      0     0       0       1   
1   2        42      16      16    16    86      0     0       0       1   
2   3        47      12      12    18    86      0     1       0       1   
3   4        78      19      16    17    86      0     0       0       1   
4   5        41      16      12    18    86      0     1       0       1   

   colgrad    edcat  
0        1  ColGrad  
1        1  ColGrad  
2        1  GradSch  
3        1  GradSch  
4        1  GradSch

In [98]:
y = socio_data['educ'].values
# X = sm.add_constant() #, 'black', 'male']])#[[x_paeduc, x_maeduc, x_black, x_male ]]
X = socio_data[['papres16','paeduc', 'maeduc']]

In [117]:
sample_inx = np.random.choice(X.shape[0], 1000)
X_sample = X.loc[sample_inx, ]

In [118]:
X_sample.shape

(1000, 3)

In [97]:
from sklearn.linear_model import LinearRegression

from sklearn.preprocessing import StandardScaler

In [128]:
y.loc[sample_inx]

AttributeError: 'numpy.ndarray' object has no attribute 'loc'

In [124]:
y = y[sample_inx]
y

IndexError: index 3917 is out of bounds for axis 1 with size 1000

In [119]:
scaler = StandardScaler()
scaler.fit(np.array(X_sample))
X_scaled = scaler.transform(X_sample)

/Users/pwong/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [120]:
X_scaled

array([[-1.88215499,  0.45199551,  0.39016785],
       [ 0.2557031 , -0.50816489,  0.95156044],
       [ 0.63746347,  1.41215591,  0.95156044],
       ...,
       [ 0.48475932,  0.45199551,  0.10947155],
       [-1.04228217, -2.4284857 , -2.1360988 ],
       [ 0.63746347, -0.26812479,  0.10947155]])

In [121]:
lr = LinearRegression().fit(X_scaled,y)

ValueError: Found input variables with inconsistent numbers of samples: [1000, 4552]

In [107]:
lr.coef_

array([0.27076852, 0.77475194, 0.93032872])

In [93]:
np.max(X)

papres16    82
paeduc      20
maeduc      20
dtype: int8

In [133]:
opt.fit(X_scaled, y, iters=1000,verbose=True)


=====
Iter 0 Loss: 182.58570559368985
[0.76198276 0.25738549 0.60715732]
coef0: 0.7619827575918958
14.635729012524113
coef1: 0.2573854854821028
11.2598307522532
coef2: 0.6071573153407719
16.233209419117728
=====
Iter 1 Loss: 182.5881241581685
[0.76051918 0.2562595  0.60553399]
coef0: 0.7605191846906434
-19.331855915975883
coef1: 0.2562595024068775
-13.707314126102188
coef2: 0.6055339943988601
-11.832315059872656
=====
Iter 2 Loss: 182.58604934348264
[0.76245237 0.25763023 0.60671723]
coef0: 0.762452370282241
27.51582708071658
coef1: 0.25763023381948774
13.41534728514853
coef2: 0.6067172259048474
11.930532200515595
=====
Iter 3 Loss: 182.5877974401426
[0.75970079 0.2562887  0.60552417]
coef0: 0.7597007875741694
16.909184581875426
coef1: 0.2562886990909729
11.660956204687068
coef2: 0.6055241726847959
29.693891072392663
=====
Iter 4 Loss: 182.59160201661794
[0.75800987 0.2551226  0.60255478]
coef0: 0.7580098691159818
-19.651751094915596
coef1: 0.2551226034705042
-43.53400261966463
coef2: 

[0.72316414 0.20133034 0.60576641]
coef0: 0.7231641386203644
-5.874898199899671
coef1: 0.20133034353943466
-10.384808083294432
coef2: 0.6057664137117137
-8.964288696343834
=====
Iter 167 Loss: 182.64194379223693
[0.72375163 0.20236882 0.60666284]
coef0: 0.7237516284403545
-83.04231616941952
coef1: 0.2023688243477641
-63.801311377927505
coef2: 0.6066628425813481
-78.86574585511836
=====
Iter 168 Loss: 182.6271104366271
[0.73205586 0.20874896 0.61454942]
coef0: 0.7320558600572964
-13.373048501175864
coef1: 0.20874895548555686
-12.469193645849606
coef2: 0.6145494171668598
-33.99424884408094
=====
Iter 169 Loss: 182.62218670009892
[0.73339316 0.20999587 0.61794884]
coef0: 0.733393164907414
18.683605732838593
coef1: 0.20999587485014182
-29.810745684833915
coef2: 0.617948842051268
-12.478808748390271
=====
Iter 170 Loss: 182.61655206075392
[0.7315248  0.21297695 0.61919672]
coef0: 0.7315248043341301
-5.53479789779127
coef1: 0.21297694941862522
-9.78362722087089
coef2: 0.6191967229261071
3.70

Iter 291 Loss: 182.60926202638936
[0.66446498 0.21115445 0.61511168]
coef0: 0.6644649766264755
-59.625359380756585
coef1: 0.21115445335568264
-12.906332081861443
coef2: 0.6151116791507794
-11.14089792172523
=====
Iter 292 Loss: 182.6071660421625
[0.67042751 0.21244509 0.61622577]
coef0: 0.6704275125645511
1.4131968816819092
coef1: 0.2124450865638688
-12.850941861772055
coef2: 0.6162257689429519
12.848824413011876
=====
Iter 293 Loss: 182.6069101398142
[0.67028619 0.21373018 0.61494089]
coef0: 0.6702861928763829
1.251819835539947
coef1: 0.213730180750046
12.798075125934975
coef2: 0.6149408865016507
18.45088423192599
=====
Iter 294 Loss: 182.6106931377509
[0.67016101 0.21245037 0.6130958 ]
coef0: 0.6701610108928289
-14.327067969939925
coef1: 0.2124503732374525
-10.158653262447
coef2: 0.613095798078458
-8.769069190322575
=====
Iter 295 Loss: 182.60856851550983
[0.67159372 0.21346624 0.6139727 ]
coef0: 0.6715937176898229
17.953787092645335
coef1: 0.2134662385636972
-13.891564051203847
coef

=====
Iter 457 Loss: 182.48928489964356
[0.64988073 0.25397507 0.67502818]
coef0: 0.649880728232631
16.358470618245168
coef1: 0.2539750677167144
-12.657203808893247
coef2: 0.6750281844110088
-10.925847461148978
=====
Iter 458 Loss: 182.48639580733538
[0.64824488 0.25524079 0.67612077]
coef0: 0.6482448811708065
-8.2315943649006
coef1: 0.25524078809760375
4.55296974254902
coef2: 0.6761207691571236
-6.625356786270494
=====
Iter 459 Loss: 182.486450256636
[0.64906804 0.25478549 0.6767833 ]
coef0: 0.6490680406072965
-19.699733572924163
coef1: 0.25478549112334886
15.703979024331609
coef2: 0.6767833048357507
-12.057479387571922
=====
Iter 460 Loss: 182.4875219226561
[0.65103801 0.25321509 0.67798905]
coef0: 0.6510380139645889
0.5620046116098439
coef1: 0.2532150932209157
-5.110603259505015
coef2: 0.6779890527745078
-4.411532949210291
=====
Iter 461 Loss: 182.4864816525209
[0.65098181 0.25372615 0.67843021]
coef0: 0.650981813503428
33.03132962150914
coef1: 0.2537261535468662
29.981367433701607


coef0: 0.6358478453197314
10.242807281511736
coef1: 0.2777935593756473
-10.730179105761701
coef2: 0.7150766745968193
-9.262417032266427
=====
Iter 579 Loss: 182.41985092596258
[0.63482356 0.27886658 0.71600292]
coef0: 0.6348235645915802
-41.76818190128345
coef1: 0.2788665772862235
-28.246583459716415
coef2: 0.716002916300046
-7.804314401976281
=====
Iter 580 Loss: 182.41711013488333
[0.63900038 0.28169124 0.71678335]
coef0: 0.6390003827817086
1.4561345843638374
coef1: 0.2816912356321951
50.04727675626319
coef2: 0.7167833477402437
87.24725029133826
=====
Iter 581 Loss: 182.43017564484336
[0.63885477 0.27668651 0.70805862]
coef0: 0.6388547693232722
-16.219316169164454
coef1: 0.2766865079565688
0.7145734852386378
coef2: 0.7080586227111099
4.356560505383605
=====
Iter 582 Loss: 182.43101777968073
[0.6404767  0.27661505 0.70762297]
coef0: 0.6404767009401887
-25.426822316119587
coef1: 0.2766150506080449
-9.80675394928928
coef2: 0.7076229666605715
-8.465305556956501
=====
Iter 583 Loss: 182.4

=====
Iter 714 Loss: 182.338745635375
[0.61623898 0.31918959 0.75938072]
coef0: 0.6162389816366101
-26.359893466517665
coef1: 0.3191895865351401
-11.689829976830739
coef2: 0.7593807234683657
-10.090798971245084
=====
Iter 715 Loss: 182.3375891917654
[0.61887497 0.32035857 0.7603898 ]
coef0: 0.6188749709832618
-37.42505444324997
coef1: 0.3203585695328232
9.826196038717194
coef2: 0.7603898033654902
-7.544530975971304
=====
Iter 716 Loss: 182.33901157123577
[0.62261748 0.31937595 0.76114426]
coef0: 0.6226174764275868
-35.65153694797128
coef1: 0.3193759499289515
-10.907695596015415
coef2: 0.7611442564630874
4.132048437788241
=====
Iter 717 Loss: 182.33930011752634
[0.62618263 0.32046672 0.76073105]
coef0: 0.626182630122384
11.070124265664102
coef1: 0.32046671948855304
-11.596861371005232
coef2: 0.7607310516193085
-10.010547375295316
=====
Iter 718 Loss: 182.3371468540684
[0.62507562 0.32162641 0.76173211]
coef0: 0.6250756176958175
-5.122710212022882
coef1: 0.3216264056256536
-40.3346764343

-55.18954038959935
coef1: 0.391286294433476
-12.888703198942865
coef2: 0.8109353814482365
-11.125680462277868
=====
Iter 870 Loss: 182.25679332225818
[0.65094175 0.39257516 0.81204795]
coef0: 0.6509417491057898
3.855556481305594
coef1: 0.3925751647533703
30.226218695994223
coef2: 0.8120479494944643
30.99295849043463
=====
Iter 871 Loss: 182.26037983183835
[0.65055619 0.38955254 0.80894865]
coef0: 0.6505561934576592
51.69431232171207
coef1: 0.3895525428837709
-12.41427888757328
coef2: 0.8089486536454209
-10.716151806806373
=====
Iter 872 Loss: 182.25664453429857
[0.64538676 0.39079397 0.81002027]
coef0: 0.6453867622254881
-12.792276694451193
coef1: 0.3907939707725282
-11.927674924709612
coef2: 0.8100202688261016
-10.296109532658626
=====
Iter 873 Loss: 182.2558153992698
[0.64666599 0.39198674 0.81104988]
coef0: 0.6466659898949332
-15.0342873416491
coef1: 0.39198673826499913
17.64607596691886
coef2: 0.8110498797793674
-2.581837049823617
=====
Iter 874 Loss: 182.2576092194571
[0.64816942 

=====
Iter 967 Loss: 182.2508763736521
[0.65498848 0.39022934 0.83114702]
coef0: 0.6549884814395641
13.552836918745104
coef1: 0.3902293352756876
76.28156809338874
coef2: 0.8311470203782257
93.54834861844066
=====
Iter 968 Loss: 182.26013821164221
[0.6536332  0.38260118 0.82179219]
coef0: 0.6536331977476896
1.284463133913532
coef1: 0.3826011784663487
19.334832517742033
coef2: 0.8217921855163817
18.93202193412532
=====
Iter 969 Loss: 182.26242322351754
[0.65350475 0.3806677  0.81989898]
coef0: 0.6535047514342982
-65.37365817545457
coef1: 0.3806676952145745
-48.20035158448403
coef2: 0.8198989833229692
-11.382564402235296
=====
Iter 970 Loss: 182.26144431988513
[0.66004212 0.38548773 0.82103724]
coef0: 0.6600421172518437
1.165417112532838
coef1: 0.3854877303730229
0.6584900558968111
coef2: 0.8210372397631928
-9.148102854147613
=====
Iter 971 Loss: 182.2609818661148
[0.65992558 0.38542188 0.82195205]
coef0: 0.6599255755405904
26.670378974282436
coef1: 0.3854218813674332
40.54205593946728
co

In [134]:
opt.coefs

array([0.67410732, 0.40010296, 0.83948579])

In [75]:
model = sm.OLS(y, X)
result = model.fit()

In [76]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.304
Model:                            OLS   Adj. R-squared:                  0.303
Method:                 Least Squares   F-statistic:                     662.0
Date:                Sun, 09 Dec 2018   Prob (F-statistic):               0.00
Time:                        19:41:14   Log-Likelihood:                -10774.
No. Observations:                4552   AIC:                         2.156e+04
Df Residuals:                    4548   BIC:                         2.158e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.8382      0.146     53.659      0.000       7.552       8.125
papres16       0.0205      0.003      6.176      0.000       0.014       0.027
paeduc         0.1801      0.013     13.726      0.000       0.154       0.206
maeduc         0.2575      0.015     17.705      0.000       0.229       0.286
==============================================================================
Omnibus:                      118.093   Durbin-Watson:                   1.825
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              233.378
Skew:                           0.169   Prob(JB):                     2.10e-51
Kurtosis:                       4.056   Cond. No.                         175.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
result.params

const       7.812613
papres16    0.019210
paeduc      0.179124
maeduc      0.253879
black      -0.346477
male        0.374384
dtype: float64

## Optimizer example

In [11]:
from pyautodiff.optimizer import Optimizer

In [20]:
import numpy as np

In [130]:
opt = Optimizer(loss = 'mse', optimizer = 'sgd',lr=0.0001)

In [77]:
y = socio_data['educ'].values
X = socio_data[['papres16','paeduc', 'maeduc']]#, 'black', 'male']]#[[x_paeduc, x_maeduc, x_black, x_male ]]

In [78]:
X_array = np.array(X)

In [79]:
X_array[:5], X[:5]

(array([[50, 16, 12],
        [42, 16, 16],
        [47, 12, 12],
        [78, 19, 16],
        [41, 16, 12]], dtype=int8),    papres16  paeduc  maeduc
 0        50      16      12
 1        42      16      16
 2        47      12      12
 3        78      19      16
 4        41      16      12)

In [53]:
np.array(y).shape, X_array.shape

((4552,), (4552, 5))

In [40]:
# np.amax(X_array, axis=0)

array([ 1., 82., 20., 20.,  1.,  1.])

In [80]:
opt.fit(X_array, y, iters=100)

/Users/pwong/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/Users/pwong/Documents/cs207-FinalProject/pyautodiff/optimizer.py:123: RuntimeWarning: overflow encountered in square
  return np.sum((y-y_preds)**2)/len(y)
/Users/pwong/Documents/cs207-FinalProject/pyautodiff/dual.py:210: RuntimeWarning: overflow encountered in double_scalars
  return Dual(self.val ** other, temp)


In [81]:
opt.coefs

array([-1.55504049e+156, -4.20604066e+155, -4.22770658e+155])

In [82]:
result.params

const       7.838184
papres16    0.020480
paeduc      0.180101
maeduc      0.257477
dtype: float64

In [36]:
from sklearn.datasets import make_regression

In [41]:
np.amax(X, axis=0)

array([3.49743749, 4.09623193, 4.04712938, 3.33472592, 3.4573205 ,
       3.05651632])

In [71]:
X,y,coef = make_regression(n_samples=4500,n_features=6,n_informative=6,coef=True)

# User defined loss function
# def user_mse(y,y_preds):
#     return (y-y_preds)**2


opt = Optimizer(loss='mse',optimizer='sgd')
opt.fit(X,y,iters=1000)

print('Actual Values:')
print('======')
print(coef)

print('Computed Values:')
print('======')
print(opt.coefs)

Actual Values:
[13.04355993 68.32081412  1.81041096 22.60987421 28.47926702 77.75625355]
Computed Values:
[13.04355992 68.32081402  1.81041105 22.60987426 28.47926695 77.75625341]
