In [14]:
import pandas as pd
import statsmodels.api as sm

df = pd.DataFrame({"A": [10,20,30,40,50], "B": [20, 30, 10, 40, 50], "C": [32, 234, 23, 23, 42523]})
sm.OLS(df['A'], sm.add_constant(df[['B', 'C']])).fit()
model = sm.OLS(formula="A ~ B + C", data=df).fit()

TypeError: __init__() missing 1 required positional argument: 'endog'

In [15]:
df['A'].

0    10
1    20
2    30
3    40
4    50
Name: A, dtype: int64

In [5]:
model.summary()

/Users/pwong/anaconda3/lib/python3.6/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      A   R-squared:                       0.579
Model:                            OLS   Adj. R-squared:                  0.158
Method:                 Least Squares   F-statistic:                     1.375
Date:                Thu, 06 Dec 2018   Prob (F-statistic):              0.421
Time:                        00:33:12   Log-Likelihood:                -18.178
No. Observations:                   5   AIC:                             42.36
Df Residuals:                       2   BIC:                             41.19
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     14.9525     17.764      0.842      0.489     -61.481      91.386
B              0.4012      0.650      0.617      0.600      -2.394       3.197
C              0.0004      0.001      0.650      0.583      -0.002       0.003
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.061
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.498
Skew:                          -0.123   Prob(JB):                        0.780
Kurtosis:                       1.474   Cond. No.                     5.21e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.21e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [7]:
socio_data = pd.read_stata('gsswide.dta')
socio_df = pd.DataFrame(data=socio_data)
# print(socio_data)

In [10]:
socio_data.dtypes

id             int16
papres16        int8
paeduc          int8
maeduc          int8
educ            int8
year            int8
black           int8
male            int8
parfor          int8
hsgrad          int8
colgrad         int8
edcat       category
dtype: object

In [ ]:
import numpy as np
>>>
>>> import statsmodels.api as sm
>>>
>>> Y = [1,3,4,5,2,3,4]
>>> X = range(1,8)
>>> X = sm.add_constant(X)
>>>
>>> model = sm.OLS(Y,X)
>>> results = model.fit()
>>> results.params
array([ 2.14285714,  0.25      ])
>>> results.tvalues
array([ 1.87867287,  0.98019606])

In [ ]:
y = socio_data['papres16']
X = sm.add_constant(socio_data[['paeduc']])#[[x_paeduc, x_maeduc, x_black, x_male ]]

In [ ]:
model = sm.OLS(socio_data['papres16'], )

In [ ]:
= sm.ols(formula="A ~ B + C", data=df).fit()

In [14]:
import matplotlib.pyplot as plt
plt.plot(result)

TypeError: float() argument must be a string or a number, not 'RegressionResultsWrapper'

In [16]:
import numpy as np
np.array(result)

array(<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x1a1bf69be0>, dtype=object)

In [19]:
numpy_matrix = socio_df.as_matrix()

In [24]:
y_educ = numpy_matrix[:,4]
y_educ

array([16, 16, 18, ..., 12, 12, 6], dtype=object)

In [27]:
x_papres = numpy_matrix[:, 1] 
x_paeduc = numpy_matrix[:, 2]
x_maeduc = numpy_matrix[:, 3]
x_black = numpy_matrix[:, 6]
x_male = numpy_matrix[:, 7]

In [28]:
educ_model = sm.ols(y_educ,[x_papres, x_paeduc, x_maeduc, x_black, x_male], 'Highest year of education', 
                     ['father occupational prestige', 'father education', 'mother education', 'black', 'male'])

ModuleNotFoundError: No module named 'ols'

In [30]:
import .ols

ModuleNotFoundError: No module named 'scipy.ols'

In [47]:
from autodiff.dual.dual import Dual
import inspect

class AutoDiff:
    def __init__(self, fn, ndim=1, multivar_list=0):
        """
        fn : function, the function of which we want to calculate the derivative
        ndim : float, the number of dimensions of the function
        l : the number of parameters in the function
            (e.g. in lambda x, y: x**2 + y**2) it would be x,y (so l = 2)
        """
        self.fn = fn
        self.ndim = ndim
        sig = inspect.signature(self.fn)
        self.l = len(list(sig.parameters))
        self.multivar_list = multivar_list

    def get_der(self, *args):
        """ Returns derivatives of the function evaluated at values given.

        INPUTS
        =======
        val : single number, a list of numbers, or a list of lists

        RETURNS
        =======
        Derivates in the same shape given

        EXAMPLE
        =======
        >>> a = AutoDiff(lambda x,y: 5*x + 4*y)
        >>> a.get_der([[6.7, 4],[2,3],[4.5,6]])
        [[5, 4], [5, 4], [5, 4]]
        """
        #self.l = len(list(args))
        #val = list(args)
        
        ders = []
        if self.ndim >1:
            for i in range(self.ndim):
                def fxn(*args):
                    return self.fn(*args)[i]
                a = AutoDiff(fxn,ndim=1)
                a.l=self.l
                ders.append(a.get_der(val))
            return ders
        else:
            if self.l >= 2 or self.multivar_list==1:
    #add list of variables, evaluated at different functions
                #for list of lists, each list evaluated at different variables
                if any(isinstance(el, list) for el in val):
                    list_der = []
                    for p in val:
                        list_der.append(self.get_der(p))
                    return list_der
                elif self.l != len(val):
                    raise Exception('Function requires {} values that correspond to the multiple variables'.format(self.l))
                else:
                    #for a list of numbers, evaluated at different variables.
                    for i in range(self.l):
                        new_val = val.copy()
                        new_val[i] = Dual(new_val[i])
                        v = self.fn(*new_val)
                        #Check if variable is in the function. (E.g., function paramaters are x, y and function is x.)
                        if type(v) is Dual:
                            ders.append(self.fn(*new_val).der)
                        else:
                            ders.append(0)
                    return ders
            #for a list of variables, evaluated in a single function.
            #if self.multivar_list = 1
                
            
            #for a list of numbers, evaluated at a single variable.
            if (isinstance(val,list)):
                for v in val:
                    a = Dual(v)
                    ders.append(self.fn(a).der)
                return ders
            else:
                a = Dual(val)
                return self.fn(a).der

In [51]:
AD = AutoDiff

def my_fn(xlist):
    val = 0
    for x in xlist:
        val += x**2
    return val

mylist = [3,2,1]
ad_my = AD(my_fn, multivar_list=1)
ad_my.get_der(mylist)

Exception: Function requires 1 values that correspond to the multiple variables

In [40]:
signatur = inspect.signature(my_fn)
len(list(signatur.parameters))

1

In [ ]:
sig = inspect.signature(self.fn)
        self.l = len(list(sig.parameters))

In [53]:
def my_fn(xlist):
    return xlist**2

mylist = [3,2,1]
ad_my = AD(my_fn)
ad_my.get_der(mylist)

[6, 4, 2]

In [54]:
def my_fxn(*args):
    tot = 0
    for a in args:
        tot += a**2
    return tot

mylist = [3,2,1]
ad_my = AD(my_fxn)
ad_my.get_der(mylist)

[6, 4, 2]

In [91]:
def sum(xs):
    cur_val = 0
    cur_der = 0
    is_dual = False
    for x in xs:
        if (isinstance(x,Dual)):
            is_dual = True
            cur_der += x.der
            cur_val += x.val
        else:
            cur_val += x
    if is_dual:
        return Dual(cur_val,cur_der)
    else:
        return cur_val

In [98]:
import autodiff.admath.admath as admath
def mse_loss_fn(X,Y):
    def func(*args):
        my_l = []
        for x in X:
            for y in Y:
                val = 0
                for x_i in x:
                    for w in args:
                        val += x_i*w
                        print('val:{}'.format(val))
                    my_l.append((y-val)**2)
        return sum(my_l)/len(Y)
    return func

X = [[1,4],[1,2],[1,3]]
y = [2,4,6]
f1 = mse_loss_fn(X, y)
fn = AD(f1)
fn.get_der([0,0])

val:<autodiff.dual.dual.Dual object at 0x1a1c10fbe0>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f8d0>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f9e8>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f4a8>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f390>
val:<autodiff.dual.dual.Dual object at 0x1a1c10fc50>
val:<autodiff.dual.dual.Dual object at 0x1a1c10fcf8>
val:<autodiff.dual.dual.Dual object at 0x1a1c10fdd8>
val:<autodiff.dual.dual.Dual object at 0x1a1c10fdd8>
val:<autodiff.dual.dual.Dual object at 0x1a1c10fbe0>
val:<autodiff.dual.dual.Dual object at 0x1a1c10fb70>
val:<autodiff.dual.dual.Dual object at 0x1a1c10fe48>
val:<autodiff.dual.dual.Dual object at 0x1a1c10feb8>
val:<autodiff.dual.dual.Dual object at 0x1a1c10ff98>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f080>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f240>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f7b8>
val:<autodiff.dual.dual.Dual object at 0x1a1c10f940>
val:<autodiff.dual.dual.Dual object at 0x1a1c1

[-120.0, -120.0]

In [73]:
def mse(X,y):
    def y_pred(*args): #where args are betas
        val = []
        for x, beta in zip(X, args):
            val += x*beta
        return val
    return y_pred

X = [[1,1],[1,2],[1,3]]
y = [2,4,6]
f1 = mse(X, y)
fn = AD(f1)
fn.get_der([0,0])

[[1, 1], [1, 1]]

In [81]:
fm = AD(mse(X,y))
fm.get_der([40,22])

[[1, 1], [1, 1]]